### ISSUE TITLE
Get "Failed to run synchronizer: File exists"

### ISSUE THREAD

**Issue by aplanas** [thkukuk/tiu#2]
Seems that I get the same `casync` error even when the tiutar was generated by `tiu`, and so using a btrfs subvolume (as noted in the readme)

Related: https://github.com/systemd/casync/issues/248

**Comment by aplanas** [comment]
This is not happening using the official TIU images from OBS (https://download.opensuse.org/repositories/home:/kukuk:/tiu/images/repo/tiu/), so is clearly something during the tiutar creation

**Comment by thkukuk** [comment]
We use only directories from now on, so this should not happen anymore.
